### ISSUE TITLE
Real time

### ISSUE THREAD

**Issue by danielfortunato** [neumicha/Blender2Helios#4]
Hi, 

Does the point cloud acquisition run in real-time?

**Comment by neumicha** [comment]
Dear Daniel,
can you describe your case of use/goal a bit more detailed?

About the runtime of converting an artificial scene to a 3D point cloud with Blender2Helios:
Blender2Helios only creates a valid Helios-compatible XML file(s) and .obj files of all the objects within a (static) Blender scene. When this is done (~few seconds up to 1 minute for 100-1000 objects) you have to apply Helios (https://www.geog.uni-heidelberg.de/gis/helios.html). Helios does the whole point cloud acquisition. For this it first creates a data structure from the XML/obj files (I think octrees?!) and afterwards performs the LiDAR simulation. On my hardware (due to corona only a laptop) this whole process takes around 5 minutes in a typical scene with a simulated Riegl VZ-400 - in reality our VZ-400 needs 3 minutes for this. With decent hardware you should be able to achieve "real-world speed".
As far is I know the Helios-team is also working on a C++ implementation. This might be faster than the current Java code.

If you ask because you want something moving in the scene: Blender2Helios currently only supports the conversion of static scenes. However, Helios itself has some possibilities to e.g. mount the scanner on a moving platform. So you just need to change the corresponding XML file manually.

I hope this answers your question.

**Comment by danielfortunato** [comment]
Greetings, 

Thanks for the response. I have a 3D environment that I built in blender for autonomous surface vehicles. And I was wondering if there were any tools available for blender that could simulate a real-time LiDAR. I tried blensor, but it takes a lot of time to acquire one frame. Are you familiar with any tool that could help me? 

Best regards.

**Comment by neumicha** [comment]
Sorry, I am only experienced with Helios for creating typical static TLS scans. And Blender2Helios only provides an interface for it - so this tool is not really point cloud related, just something like a file format converter.
This short video shows many features of Helios (including vehicle mounted scanners): https://www.youtube.com/watch?v=1SOg7b5q4ak&feature=youtu.be
Maybe this is one way to go. But I am not sure how fast it is and I think you have to provide the path of the vehicle at the beginning and only get the point cloud results at the end. As it is open source there may be the possibility to change the behaviour more or less easily.
